version: '2'

services:
  web:
    image: larryms/lnchello
    ports:
     - "8080:5000"
    depends_on:
     - redis

  redis:
    image: redis

  omsagent:
    image: "microsoft/oms"
    privileged: true
    ports:
      - "25225:25225"
    volumes:  
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WSID: <replace>
      KEY:  <replace>
    restart: on-failure
